### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ItelSunday**
bitmoji

### CODE REVIEW

**Comment by YanrongXu** [comment]
The code is still not render yet,

**Comment by YanrongXu** [comment]
screencapture-rl7rkjoj4n-codesandbox-io-2019-02-28-13_33_33
that is only thing i see

**Comment by ItelSunday** [comment]
> The code is still not render yet,

**Comment by ItelSunday** [comment]
> The code is still not render yet,

currently working on it

**Pull request closed without merging**
